# Exploratory Data Analysis: Data Cleaning

## Objectives of the Practical Work
* Practice identifying and filling missing values in the data.
* Practice converting data types.
* Practice identifying and handling anomalous (outlier) values in the data.
* Prepare the dataframe for the feature engineering stage.

## Task

In this practical work, I continue exploring and preparing the dataset for the modeling stage. I focus on handling missing values in several variables, converting data types where necessary, and detecting and processing outliers in the data.

The dataset I am working with contains a small sample of used cars listed for sale in the United States. Based on this data, I will later build a classification model that predicts the price category of a used car depending on the characteristics of the vehicle.

## Dataset Description:
- `id`: record identifier;
- `url`: URL of the listing;
- `region`: region where the vehicle is listed;
- `region_url`: URL of the region;
- `price`: price of the vehicle;
- `year`: year of manufacture;
- `manufacturer`: vehicle manufacturer;
- `model`: vehicle model;
- `condition`: condition of the vehicle;
- `cylinders`: number of engine cylinders;
- `fuel`: fuel type;
- `odometer`: mileage (number of miles traveled);
- `title_status`: vehicle title status;
- `transmission`: transmission type;
- `VIN`: vehicle identification number;
- `drive`: drivetrain type;
- `size`: vehicle size category;
- `type`: vehicle body type;
- `paint_color`: color of the vehicle;
- `image_url`: URL of the vehicle image;
- `description`: description provided in the listing;
- `county`: county;
- `state`: state;
- `lat`: latitude;
- `long`: longitude;
- `posting_date`: date when the listing was posted;
- `price_category`: price category of the vehicle.

## What This Practical Work Includes
1. Loading the dataset and becoming familiar with its structure.
2. Exploring the dataset variables to identify missing values.
3. Handling missing values depending on the type of variable.
4. Converting data types where necessary.
5. Analyzing the data for anomalous values and correcting outliers.

## Importing the Pandas Library

In [1]:
import pandas as pd

### Task 1. Loading the Dataset and Reviewing Missing Values

1. In this step, I load the dataset from data/df_out.csv and display the first five records to get an initial overview of the data.

In [2]:
df = pd.read_csv('data/df_out.csv')
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,2021-04-17 16:30:50+00:00
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium,2021-05-03 19:40:21+00:00
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,2021-04-28 10:52:20+00:00
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,2021-04-17 14:08:57+00:00
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium,2021-05-03 22:32:06+00:00

2. Display the information about the dataframe and examine the remaining missing values.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9902 entries, 0 to 9901
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              9902 non-null   int64
 1   url             9902 non-null   object
 2   region          9902 non-null   object
 3   region_url      9902 non-null   object
 4   price           9902 non-null   int64
 5   year            9868 non-null   float64
 6   manufacturer    9902 non-null   object
 7   model           9776 non-null   object
 8   fuel            9841 non-null   object
 9   odometer        9902 non-null   int64
 10  title_status    9738 non-null   object
 11  transmission    9902 non-null   object
 12  image_url       9902 non-null   object
 13  description     9902 non-null   object
 14  state           9902 non-null   object
 15  lat             9902 non-null   float64
 16  long            9902 non-null   float64
 17  posting_date    9902 non-null   object
 18  price_category  9902 non-null   object
 19  date            9902 non-null   object
dtypes: float64(3), int64(3), object(14)
memory usage: 1.5+ MB

3. Display the number of fully completed records and their percentage of the total dataset. Use the materials from the video as a reference.

In [4]:
# Removing Rows with Missing Values
df_clean = df.dropna()
# Counting the Number of Rows After Removing Missing Values
num_filled_rows = len(df_clean)
# Size of DataFrame
total_rows = len(df)
percentage_filled = round(((num_filled_rows / total_rows) * 100), 2)
print('Number of Complete Rows: ', num_filled_rows)
print('Percentage of Fully Completed Rows: ', percentage_filled, '%')

Number of Complete Rows:  9543
Percentage of Fully Completed Rows:  96.37 %

4. In this step, I calculate the percentage of missing values for each feature, store the result in a variable, and display it sorted in descending order by the percentage of missing values. I also use the appropriate sorting parameter as shown in the video materials.

In [5]:
missing_percentage = round((df.isnull().sum() / len(df)) * 100, 2)
missing_percentage_sorted = missing_percentage.sort_values(ascending=False)
print('Percentage of Missing Values for Each Feature: ', missing_percentage_sorted)

Percentage of Missing Values for Each Feature:  title_status      1.66
model             1.27
fuel              0.62
year              0.34
region_url        0.00
region            0.00
url               0.00
id                0.00
manufacturer      0.00
price             0.00
odometer          0.00
transmission      0.00
image_url         0.00
description       0.00
state             0.00
lat               0.00
long              0.00
posting_date      0.00
price_category    0.00
date              0.00
dtype: float64

5. In this step, I display the list of all features that contain missing values. I use the results from the previous step to identify and sort the features that meet this condition.

In [6]:
columns_with_missing_values = missing_percentage_sorted[missing_percentage_sorted > 0]
print('List of All Features Containing Missing Values: ', columns_with_missing_values)

List of All Features Containing Missing Values:  title_status    1.66
model           1.27
fuel            0.62
year            0.34
dtype: float64

### Task 2. Handling Missing Values in the Vehicle's Year of Manufacture

1. In this step, I display the number of values for the vehicle's year of manufacture, including missing values.

In [7]:
year_total_rows = len(df['year'])
year_total_rows

9902

2. In this step, I display the number of missing values in the vehicle's year of manufacture.

In [9]:
num_empty_car_rows = df['year'].isna().sum()
print('Number of Missing Values in the Vehicles Year of Manufacture: ', num_empty_car_rows)

Number of Missing Values in the Vehicles Year of Manufacture:  34

3. In this step, I display the descriptive statistics for the vehicle's year of manufacture.

In [10]:
df['year'].describe()

count    9868.000000
mean     2010.909708
std         9.705988
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

4. In this step, I display the records in which the vehicle's year of manufacture is missing and examine the data to decide which strategy can be applied to handle these missing values.

In [11]:
empty_car_rows = df[df['year'].isna()]
empty_car_rows

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
342,7304102133,https://wenatchee.craigslist.org/ctd/d/wenatch...,wenatchee,https://wenatchee.craigslist.org,35880,NaN,other,500,gas,13508,clean,automatic,https://images.craigslist.org/00J0J_6IMoEUzIIM...,2019 *Ram* *1500* Big Horn/Lone Star 4x2 Quad ...,wa,47.434493,-120.320759,2021-04-09T06:31:03-0700,high,2021-04-09 13:31:03+00:00
418,7316337069,https://lasvegas.craigslist.org/ctd/d/scottsda...,las vegas,https://lasvegas.craigslist.org,84995,NaN,other,Super Duty F-350 SRW,diesel,1268,clean,automatic,https://images.craigslist.org/00x0x_iQCC0Ef28S...,2020 *Ford* *Super Duty F-350 SRW* 1K MILES. B...,nv,33.458277,-111.925970,2021-05-03T11:31:39-0700,high,2021-05-03 18:31:39+00:00
423,7315662117,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,43900,NaN,other,Grand Caravan,NaN,21,clean,automatic,https://images.craigslist.org/00f0f_7AwipNocNH...,"2019 *Dodge* *Grand Caravan* SE - $43,900Call ...",co,39.674406,-104.998604,2021-05-02T01:11:33-0600,high,2021-05-02 07:11:33+00:00
697,7316199009,https://nashville.craigslist.org/ctd/d/nashvil...,nashville,https://nashville.craigslist.org,28498,NaN,other,olet Silverado 1500,NaN,59246,NaN,automatic,https://images.craigslist.org/00T0T_dZ7nOXskCS...,2019 *Chevrolet* *Silverado 1500* 2019 CHEVROL...,tn,36.138022,-86.732261,2021-05-03T10:00:40-0500,high,2021-05-03 15:00:40+00:00
887,7316840794,https://denver.craigslist.org/ctd/d/american-f...,denver,https://denver.craigslist.org,60900,NaN,other,F-150,gas,6110,clean,automatic,https://images.craigslist.org/01616_bpzSdSRTbx...,"2020 *Ford* *F-150* PLATINUM FX4 Truck - $60,9...",co,40.362248,-111.785947,2021-05-04T12:11:22-0600,high,2021-05-04 18:11:22+00:00
900,7311915616,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,67900,NaN,other,Odyssey,gas,21,clean,automatic,https://images.craigslist.org/00404_erlbeKWEkn...,2020 *Honda* *Odyssey* EX-L w/Navi/RES Automat...,co,39.674406,-104.998604,2021-04-24T10:41:06-0600,high,2021-04-24 16:41:06+00:00
998,7306735187,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,38900,NaN,other,Grand Caravan,NaN,21,clean,automatic,https://images.craigslist.org/00F0F_3T6FM0XMZW...,"2019 *Dodge* *Grand Caravan* SE - $38,900Call ...",co,39.674406,-104.998604,2021-04-14T10:51:36-0600,high,2021-04-14 16:51:36+00:00
1208,7309954650,https://gainesville.craigslist.org/ctd/d/gaine...,gainesville,https://gainesville.craigslist.org,24975,NaN,other,CR-V,gas,44128,clean,automatic,https://images.craigslist.org/00000_2TUtAgLlCR...,"2019 *Honda* *CR-V* EX 2WD SUV - $24,975Call o...",fl,29.676827,-82.319202,2021-04-20T14:46:55-0400,high,2021-04-20 18:46:55+00:00
1308,7313865045,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,47900,NaN,other,a Sienna,gas,43701,clean,automatic,https://images.craigslist.org/00o0o_8XYp4Zygdj...,2018 *Toyota* *Sienna* LE Automatic Access Sea...,co,39.674406,-104.998604,2021-04-28T10:12:14-0600,high,2021-04-28 16:12:14+00:00
1828,7303344554,https://daytona.craigslist.org/ctd/d/new-smyrn...,daytona beach,https://daytona.craigslist.org,35850,NaN,other,Transit Cargo Van,gas,567,clean,automatic,https://images.craigslist.org/00a0a_d4XVrHnlxl...,"2020 *Ford* *Transit Cargo Van* T-250 148"" WB*...",fl,29.046240,-80.934561,2021-04-07T17:10:06-0400,high,2021-04-07 21:10:06+00:00
2270,7311762820,https://huntsville.craigslist.org/ctd/d/new-ca...,huntsville / decatur,https://huntsville.craigslist.org,29875,NaN,other,a Camry,gas,46947,clean,automatic,https://images.craigslist.org/01313_9nQ5n8dbnZ...,2019 *Toyota* *Camry* XSE Automatic Sedan - $2...,al,33.669601,-86.817617,2021-04-24T04:50:56-0500,high,2021-04-24 09:50:56+00:00
2481,7315662074,https://santafe.craigslist.org/ctd/d/denver-20...,santa fe / taos,https://santafe.craigslist.org,43900,NaN,other,Grand Caravan,NaN,21,clean,automatic,https://images.craigslist.org/00f0f_7AwipNocNH...,"2019 *Dodge* *Grand Caravan* SE - $43,900Call ...",nm,39.674406,-104.998604,2021-05-02T01:10:47-0600,high,2021-05-02 07:10:47+00:00
2603,7314588156,https://inlandempire.craigslist.org/ctd/d/hesp...,inland empire,https://inlandempire.craigslist.org,2599,NaN,other,olet Impala,other,1,clean,other,https://images.craigslist.org/00P0P_dKsEWbujM0...,Chevrolet Impala * AUCTION PRICES TO THE PUBL...,ca,34.451930,-117.287060,2021-04-29T16:19:54-0700,low,2021-04-29 23:19:54+00:00
2792,7310250813,https://omaha.craigslist.org/ctd/d/council-blu...,omaha / council bluffs,https://omaha.craigslist.org,28995,NaN,other,cadia,gas,3851,NaN,automatic,https://images.craigslist.org/00j0j_6hfE9qI1CV...,2019 *GMC* *Acadia* AWD 4dr SLT w/SLT-1 SUV - ...,ia,41.229172,-95.852118,2021-04-21T07:21:00-0500,high,2021-04-21 12:21:00+00:00
2931,7306678710,https://gainesville.craigslist.org/ctd/d/gaine...,gainesville,https://gainesville.craigslist.org,26975,NaN,other,n Maxima,gas,28367,clean,automatic,https://images.craigslist.org/01010_4uw9b06xiS...,2018 *Nissan* *Maxima* SR 3.5L Midnight Editio...,fl,29.676827,-82.319202,2021-04-14T11:25:14-0400,high,2021-04-14 15:25:14+00:00
3263,7316562384,https://honolulu.craigslist.org/oah/ctd/d/hono...,hawaii,https://honolulu.craigslist.org,37500,NaN,other,Grand Cherokee,NaN,26608,clean,automatic,https://images.craigslist.org/01111_h3zrI9JPSH...,2018 *Jeep* *Grand Cherokee* High Altitude 4x2...,hi,21.318059,-157.865187,2021-05-03T16:10:46-1000,high,2021-05-04 02:10:46+00:00
3476,7307209305,https://northmiss.craigslist.org/ctd/d/vicksbu...,north mississippi,https://northmiss.craigslist.org,64900,NaN,other,500,diesel,12338,NaN,automatic,https://images.craigslist.org/00E0E_hZTYK06AGo...,2020 *Ram* *3500* RAM 3500 DUALLY 4X4 CUMMINS ...,ms,32.332046,-90.857163,2021-04-15T10:45:56-0500,high,2021-04-15 15:45:56+00:00
3488,7304711487,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,67900,NaN,other,Odyssey,gas,21,clean,automatic,https://images.craigslist.org/00404_erlbeKWEkn...,2020 *Honda* *Odyssey* EX-L w/Navi/RES Automat...,co,39.674406,-104.998604,2021-04-10T10:12:15-0600,high,2021-04-10 16:12:15+00:00
3634,7309869204,https://scottsbluff.craigslist.org/ctd/d/denve...,scottsbluff / panhandle,https://scottsbluff.craigslist.org,48900,NaN,other,Grand Caravan,NaN,19,clean,automatic,https://images.craigslist.org/00V0V_72KAx8GRuN...,2019 *Dodge* *Grand Caravan* SE Plus Wagon - $...,ne,39.674406,-104.998604,2021-04-20T10:41:16-0600,high,2021-04-20 16:41:16+00:00
4178,7304693422,https://shreveport.craigslist.org/ctd/d/vicksb...,shreveport,https://shreveport.craigslist.org,53700,NaN,other,ierra 1500,gas,35676,NaN,automatic,https://images.craigslist.org/00O0O_cpIkn2jwHN...,2020 *GMC* *Sierra 1500* SIERRA 1500 AT4 4X4 5...,la,32.332046,-90.857163,2021-04-10T10:44:02-0500,high,2021-04-10 15:44:02+00:00
6055,7310371320,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,49900,NaN,other,Enclave,gas,10345,clean,automatic,https://images.craigslist.org/00M0M_sPt1lwAVRY...,2018 *Buick* *Enclave* FWD 4dr Essence SUV - $...,co,39.674406,-104.998604,2021-04-21T10:12:30-0600,high,2021-04-21 16:12:30+00:00
6130,7309904568,https://omaha.craigslist.org/ctd/d/omaha-2020-...,omaha / council bluffs,https://omaha.craigslist.org,25399,NaN,other,Envision,NaN,8492,rebuilt,automatic,https://images.craigslist.org/01515_geiPTG1MZG...,2020 *Buick* *Envision* AWD 4dr Essence SUV - ...,ia,41.207382,-96.023096,2021-04-20T12:31:36-0500,high,2021-04-20 17:31:36+00:00
6254,7315207437,https://huntsville.craigslist.org/ctd/d/new-ca...,huntsville / decatur,https://huntsville.craigslist.org,35495,NaN,other,Series,gas,14000,clean,automatic,https://images.craigslist.org/01212_85QVVsEWjT...,"2020 *BMW* *3 Series* 330i Sedan - $35,495Call...",al,33.669601,-86.817617,2021-05-01T04:50:32-0500,high,2021-05-01 09:50:32+00:00
7122,7310924082,https://omaha.craigslist.org/ctd/d/omaha-2018-...,omaha / council bluffs,https://omaha.craigslist.org,12995,NaN,other,u Impreza,gas,16740,rebuilt,automatic,https://images.craigslist.org/01212_dEfENLNXWW...,2018 *Subaru* *Impreza* 2.0i 4-door CVT Sedan ...,ia,41.207382,-96.023096,2021-04-22T12:20:37-0500,medium,2021-04-22 17:20:37+00:00
7567,7316247218,https://lasvegas.craigslist.org/ctd/d/scottsda...,las vegas,https://lasvegas.craigslist.org,69995,NaN,other,F-150,gas,412,clean,automatic,https://images.craigslist.org/00n0n_kNzqmJoY2a...,2021 *Ford* *F-150* NEW 2021 FORD F150 SUPERCR...,nv,33.458277,-111.925970,2021-05-03T09:15:32-0700,high,2021-05-03 16:15:32+00:00
7730,7314898718,https://gainesville.craigslist.org/ctd/d/gaine...,gainesville,https://gainesville.craigslist.org,38975,NaN,other,500,gas,28689,clean,automatic,https://images.craigslist.org/00e0e_3SqmUoLwUf...,2019 *Ram* *2500* Tradesman 4x2 Crew Cab 8' Bo...,fl,29.676827,-82.319202,2021-04-30T13:32:48-0400,high,2021-04-30 17:32:48+00:00
7734,7314454466,https://billings.craigslist.org/ctd/d/denver-2...,billings,https://billings.craigslist.org,49900,NaN,other,a Sienna,gas,34294,clean,automatic,https://images.craigslist.org/00707_lMMxHyLoAR...,2019 *Toyota* *Sienna* LE Automatic Access Sea...,mt,39.674406,-104.998604,2021-04-29T13:00:48-0600,high,2021-04-29 19:00:48+00:00
8437,7310829676,https://tucson.craigslist.org/ctd/d/tempe-2020...,tucson,https://tucson.craigslist.org,83877,NaN,other,ierra 2500HD,diesel,25363,NaN,automatic,https://images.craigslist.org/00A0A_nd5C1ILCvJ...,2020 *GMC* *Sierra 2500HD* LIFTED - AT4 Editio...,az,33.437098,-111.925724,2021-04-22T07:50:52-0700,high,2021-04-22 14:50:52+00:00
8714,7316852999,https://memphis.craigslist.org/ctd/d/memphis-2...,memphis,https://memphis.craigslist.org,19979,NaN,other,CX-5,gas,17183,clean,automatic,https://images.craigslist.org/00x0x_1sp7mb28W4...,"2019 *Mazda* *CX-5* Sport FWD SUV - $19,979Cal...",tn,35.191437,-89.894973,2021-05-04T13:30:34-0500,medium,2021-05-04 18:30:34+00:00
9237,7316270709,https://denver.craigslist.org/ctd/d/denver-201...,denver,https://denver.craigslist.org,49900,NaN,other,a Sienna,gas,34294,clean,automatic,https://images.craigslist.org/00707_lMMxHyLoAR...,2019 *Toyota* *Sienna* LE Automatic Access Sea...,co,39.674406,-104.998604,2021-05-03T10:50:33-0600,high,2021-05-03 16:50:33+00:00
9454,7312938642,https://lasvegas.craigslist.org/ctd/d/scottsda...,las vegas,https://lasvegas.craigslist.org,67995,NaN,other,olet Silverado 1500,gas,7511,clean,automatic,https://images.craigslist.org/00M0M_74pDndl5gQ...,2020 *Chevrolet* *Silverado 1500* 6.2L HIGH CO...,nv,33.458277,-111.925970,2021-04-26T11:30:40-0700,high,2021-04-26 18:30:40+00:00
9626,7309216259,https://omaha.craigslist.org/ctd/d/omaha-2019-...,omaha / council bluffs,https://omaha.craigslist.org,29995,NaN,other,Enclave,gas,1036,rebuilt,automatic,https://images.craigslist.org/01010_1PAwiL9HwM...,2019 *Buick* *Enclave* AWD 4dr Essence SUV - $...,ia,41.207382,-96.023096,2021-04-19T09:30:41-0500,high,2021-04-19 14:30:41+00:00
9752,7316246632,https://sanantonio.craigslist.org/ctd/d/scotts...,san antonio,https://sanantonio.craigslist.org,49995,NaN,other,500,gas,19078,clean,automatic,https://images.craigslist.org/00p0p_lva0tqTnF1...,2019 *Ram* *1500* LIFTED 2019 RAM 1500 WITH BU...,tx,33.458277,-111.925970,2021-05-03T11:14:44-0500,high,2021-05-03 16:14:44+00:00
9855,7314033574,https://inlandempire.craigslist.org/ctd/d/scot...,inland empire,https://inlandempire.craigslist.org,54995,NaN,other,F-150,gas,180,clean,automatic,https://images.craigslist.org/00d0d_92wTNhRT7B...,2020 *Ford* *F-150* 180 MILES. LIFTED FORD F15...,ca,33.458277,-111.925970,2021-04-28T13:51:27-0700,high,2021-04-28 20:51:27+00:00

5. In this step, I handle the missing values by removing the records where the vehicle's year of manufacture is not specified. I then save the updated dataframe and display its dimensions.

In [12]:
df_clean_year = df.dropna(subset=['year'])
df_clean_year

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,diesel,27442,clean,other,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,2021-04-17 16:30:50+00:00
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium,2021-05-03 19:40:21+00:00
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,gas,14048,clean,other,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,2021-04-28 10:52:20+00:00
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,gas,117291,clean,automatic,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,2021-04-17 14:08:57+00:00
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,gas,8000,clean,automatic,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium,2021-05-03 22:32:06+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9897,7304876387,https://chautauqua.craigslist.org/ctd/d/falcon...,chautauqua,https://chautauqua.craigslist.org,4495,2002.0,toyota,rav4,gas,150000,clean,automatic,https://images.craigslist.org/00n0n_aaEBqmzz5Z...,Transmission:Automatic Exterior Color:WHITE In...,ny,42.123900,-79.189500,2021-04-10T16:33:57-0400,low,2021-04-10 20:33:57+00:00
9898,7316152972,https://binghamton.craigslist.org/ctd/d/roches...,binghamton,https://binghamton.craigslist.org,14495,2008.0,jeep,wrangler,gas,113573,clean,other,https://images.craigslist.org/00000_9ZNVdXaiei...,2008 Jeep Wrangler X Offered by: R&L Auto -- ...,ny,43.216990,-77.755610,2021-05-03T09:36:30-0400,medium,2021-05-03 13:36:30+00:00
9899,7310993818,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,8995,2011.0,audi,a3 2.0t premium plus pzev,gas,150184,clean,automatic,https://images.craigslist.org/00X0X_k5JiZDDyqM...,2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...,or,44.925908,-122.982753,2021-04-22T12:14:01-0700,low,2021-04-22 19:14:01+00:00
9900,7306637427,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,31900,2015.0,porsche,cayenne,hybrid,61943,clean,automatic,https://images.craigslist.org/00O0O_gBihGEQxYT...,"2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...",wi,43.029559,-89.397796,2021-04-14T09:14:42-0500,high,2021-04-14 14:14:42+00:00
9901,7311960763,https://norfolk.craigslist.org/ctd/d/chesapeak...,norfolk / hampton roads,https://norfolk.craigslist.org,31990,2017.0,ram,1500 crew cab big horn,gas,35921,clean,other,https://images.craigslist.org/00c0c_4rTlvLXy36...,Carvana is the safer way to buy a car During t...,va,36.670000,-76.300000,2021-04-24T13:50:49-0400,high,2021-04-24 17:50:49+00:00

6. In this step, I display the number of missing values in the vehicle's year of manufacture for the updated dataframe.

In [13]:
count_empty_year_values = df_clean_year['year'].isna().sum()
print("Number of Missing Values in the `year` Column:", count_empty_year_values)

Number of Missing Values in the `year` Column: 0

### Task 3. Handling Missing Values in the Fuel Type

1. In this step, I display the number of values for the fuel type, including missing values, and pay attention to the number of missing entries.

In [14]:
df['fuel'].value_counts(dropna=False)

fuel
gas         8321
other        726
diesel       646
hybrid       104
NaN           61
electric      44
Name: count, dtype: int64

2. In this step, I display the descriptive statistics for the fuel type variable.

In [15]:
df['fuel'].describe()

count     9841
unique       5
top        gas
freq      8321
Name: fuel, dtype: object

3. In this step, I display the records where the fuel type is missing and examine the data to determine which strategy can be applied to handle these missing values.

In [16]:
empty_fuel = df[df['fuel'].isna()]
empty_fuel

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,60023,clean,automatic,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium,2021-05-03 19:40:21+00:00
32,7309910590,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,4977,2001.0,toyota,camry solara 2dr cpe se v6 auto (natl),NaN,193242,clean,automatic,https://images.craigslist.org/00F0F_ebtJlxCQjv...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-20T10:40:15-0700,low,2021-04-20 17:40:15+00:00
78,7314559074,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,27977,2009.0,ford,"f-150 4wd supercrew 145"" platinum",NaN,79522,clean,automatic,https://images.craigslist.org/00L0L_khoMmqXaSJ...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-29T15:15:30-0700,high,2021-04-29 22:15:30+00:00
273,7315141987,https://honolulu.craigslist.org/oah/ctd/d/fort...,hawaii,https://honolulu.craigslist.org,29888,2019.0,nissan,frontier crew cab 4x2 sv auto,NaN,10679,clean,automatic,https://images.craigslist.org/00F0F_d9wEXQuSyu...,***Call Us for more information at: 877-262-34...,hi,21.344376,-157.896975,2021-04-30T15:50:19-1000,high,2021-05-01 01:50:19+00:00
423,7315662117,https://westslope.craigslist.org/ctd/d/denver-...,western slope,https://westslope.craigslist.org,43900,NaN,other,Grand Caravan,NaN,21,clean,automatic,https://images.craigslist.org/00f0f_7AwipNocNH...,"2019 *Dodge* *Grand Caravan* SE - $43,900Call ...",co,39.674406,-104.998604,2021-05-02T01:11:33-0600,high,2021-05-02 07:11:33+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8682,7313576130,https://cnj.craigslist.org/ctd/d/parlin-2012-j...,central NJ,https://cnj.craigslist.org,23500,2012.0,jeep,wrangler unlimited 4wd 4dr sahara,NaN,105927,clean,automatic,https://images.craigslist.org/00u0u_erwAahcIeQ...,***Call Us for more information at: 732-316-55...,nj,40.468650,-74.296990,2021-04-27T18:15:18-0400,high,2021-04-27 22:15:18+00:00
9351,7309365699,https://fortmyers.craigslist.org/chl/ctd/d/bra...,ft myers / SW florida,https://fortmyers.craigslist.org,14997,2010.0,ford,e-350,NaN,153120,clean,manual,https://images.craigslist.org/00606_hQvq6K6D4p...,"2010 *Ford* *E-350* 12 Passenger Van - $14,997...",fl,27.479823,-82.571497,2021-04-19T14:01:14-0400,medium,2021-04-19 18:01:14+00:00
9541,7313475467,https://eugene.craigslist.org/ctd/d/eugene-201...,eugene,https://eugene.craigslist.org,9979,2012.0,chevrolet,equinox awd 4dr lt w/1lt,NaN,165554,clean,automatic,https://images.craigslist.org/00q0q_haS6HKqYq4...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-27T12:10:24-0700,medium,2021-04-27 19:10:24+00:00
9708,7313949726,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,8900,2012.0,honda,accord,NaN,95674,NaN,other,https://images.craigslist.org/01212_dsfYRNhxfd...,Car Starz Call Sales at 717-401-4221 2012 Hond...,pa,41.261540,-78.704520,2021-04-28T14:25:32-0400,low,2021-04-28 18:25:32+00:00
9718,7314349617,https://eugene.craigslist.org/ctd/d/eugene-200...,eugene,https://eugene.craigslist.org,11976,2008.0,acura,mdx 4wd 4dr,NaN,156801,clean,automatic,https://images.craigslist.org/00K0K_8iyrQ1sWEh...,***Call Us for more information at: 541-228-94...,or,44.076513,-123.150156,2021-04-29T09:05:16-0700,medium,2021-04-29 16:05:16+00:00

4. In this step, I handle the missing values by filling the empty entries in the fuel type column with the value other and save the changes. Note that the missing values are not filled with the most common value in the dataset.

In [17]:
df['fuel'] = df['fuel'].fillna('other')

5. In this step, I display the number of missing values in the fuel type column for the updated dataframe.

In [18]:
count_empty_fuel_values = df['fuel'].isna().sum()
print("Number of Missing Values in the `fuel` Column:", count_empty_fuel_values)

Number of Missing Values in the `fuel` Column: 0

In [19]:
df['fuel'].value_counts()

fuel
gas         8321
other        787
diesel       646
hybrid       104
electric      44
Name: count, dtype: int64

### Task 4. Handling Missing Values in the Vehicle Model

1. In this step, I display the number of values for the vehicle model, including missing values, and pay attention to the number of missing entries.

In [20]:
df['model'].value_counts(dropna=False)

model
f-150                                                                                                   148
NaN                                                                                                     126
silverado 1500                                                                                          106
1500                                                                                                    100
camry                                                                                                    76
                                                                                                       ...
gle 350 4matic                                                                                            1
500 pop                                                                                                   1
e-series van universal by glaval designer luxury series conversion leather 16" dvd limo lighting bed      1
g. caravan se                                                                                             1
silverado 2500hd 4x4                                                                                      1
Name: count, Length: 3458, dtype: int64

2. In this step, I display the descriptive statistics for the vehicle model variable.

In [21]:
df['model'].describe()

count      9776
unique     3457
top       f-150
freq        148
Name: model, dtype: object

3. In this step, I display the records where the vehicle model is missing and examine the data to determine which strategy can be applied to handle these missing values.

In [22]:
df[df['model'].isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
67,7316913641,https://ventura.craigslist.org/cto/d/camarillo...,ventura county,https://ventura.craigslist.org,3000,2005.0,rover,NaN,gas,165206,clean,automatic,https://images.craigslist.org/00S0S_b3yx6L4N2S...,2005 Range Rover HSE Changed Oil and now engi...,ca,34.219565,-119.001986,2021-05-04T13:11:15-0700,low,2021-05-04 20:11:15+00:00
140,7316550853,https://chicago.craigslist.org/chc/cto/d/midlo...,chicago,https://chicago.craigslist.org,3000,2006.0,jeep,NaN,gas,132000,clean,automatic,https://images.craigslist.org/01111_kNv3EKjH4H...,SUPER CLEAN 2006 JEEP LIBEERY RANAGADE 4X4 O...,il,41.618957,-87.726334,2021-05-03T20:33:40-0500,low,2021-05-04 01:33:40+00:00
149,7303575863,https://worcester.craigslist.org/ctd/d/fitchbu...,worcester / central MA,https://worcester.craigslist.org,7800,2007.0,gmc,NaN,gas,190000,clean,automatic,https://images.craigslist.org/00f0f_iWjiToqea2...,2007 gmc with plow leather loaded nice truck r...,ma,42.579600,-71.803100,2021-04-08T09:10:07-0400,low,2021-04-08 13:10:07+00:00
198,7315267860,https://gainesville.craigslist.org/ctd/d/kissi...,gainesville,https://gainesville.craigslist.org,19200,2012.0,ram,NaN,gas,121371,clean,automatic,https://images.craigslist.org/00W0W_hHV4D0Po0G...,2012 RAM 1500 Laramie Crew Cab 2WD Offered...,fl,28.329026,-81.404237,2021-05-01T10:05:17-0400,medium,2021-05-01 14:05:17+00:00
249,7316024407,https://reading.craigslist.org/ctd/d/paterson-...,reading,https://reading.craigslist.org,18695,2007.0,ram,NaN,diesel,220019,clean,automatic,https://images.craigslist.org/00n0n_jgq4eOvH7I...,2007 Dodge Ram 2500 SLT 4x4 Quad Cab Cummins D...,pa,40.894535,-74.152367,2021-05-02T21:06:09-0400,medium,2021-05-03 01:06:09+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9469,7314341390,https://desmoines.craigslist.org/cto/d/urbanda...,des moines,https://desmoines.craigslist.org,8000,2007.0,toyota,NaN,gas,85285,clean,automatic,https://images.craigslist.org/00K0K_aMoJgOIueB...,Toyota has been owned by non smoker with no pe...,ia,41.629500,-93.723000,2021-04-29T10:50:54-0500,low,2021-04-29 15:50:54+00:00
9521,7304358131,https://vermont.craigslist.org/ctd/d/salem-201...,vermont,https://vermont.craigslist.org,19944,2012.0,ram,NaN,gas,73082,clean,automatic,https://images.craigslist.org/00A0A_bfCaGJ20IX...,2012 RAM 1500 4WD REGULAR CAB SHORT BED 5.7 HE...,vt,42.788204,-71.233728,2021-04-09T16:24:23-0400,medium,2021-04-09 20:24:23+00:00
9573,7309686008,https://louisville.craigslist.org/cto/d/radcli...,louisville,https://louisville.craigslist.org,1600,2005.0,gmc,NaN,gas,52536,clean,automatic,https://images.craigslist.org/01111_99unV6cYER...,GMC Savana PRO AWD cargo van has been driven l...,ky,37.858900,-86.006900,2021-04-20T04:48:30-0400,low,2021-04-20 08:48:30+00:00
9828,7316447901,https://tulsa.craigslist.org/cto/d/tulsa-2017-...,tulsa,https://tulsa.craigslist.org,65000,2017.0,rover,NaN,gas,47000,clean,automatic,https://images.craigslist.org/00s0s_iGpmplDL99...,"2017 Range Rover HSE, supercharged V8, silver ...",ok,36.126200,-95.940800,2021-05-03T16:37:36-0500,high,2021-05-03 21:37:36+00:00
9874,7316458200,https://portland.craigslist.org/mlt/cto/d/port...,portland,https://portland.craigslist.org,18500,1972.0,chevrolet,NaN,gas,75000,clean,automatic,https://images.craigslist.org/00x0x_7FqS8iHJst...,1972 classic Chevrolet pick up custom deluxe ...,or,45.494960,-122.666988,2021-05-03T14:58:34-0700,medium,2021-05-03 21:58:34+00:00

4. If the vehicle description is examined in more detail, it might be possible to recover the car model from it. For now, I handle the missing values by filling the empty entries in the vehicle model column with the value `other` and save the changes. Note that once again the missing values are not filled with the most common value in the dataset.

In [23]:
df['model'] = df['model'].fillna('other')

5. In this step, I display the number of missing values in the vehicle model column for the updated dataframe.

In [24]:
 empty_model = df['model'].isna().sum()
print("Number of Missing Values in the model Column:", empty_model)

Number of Missing Values in the model Column: 0

### Task 5. Handling Missing Values in Vehicle Title Status

1. In this step, I display the number of values for the vehicle title status, including missing values, and pay attention to the number of missing entries.

In [25]:
df['title_status'].value_counts(dropna=False)

title_status
clean         9423
rebuilt        171
NaN            164
salvage         91
lien            35
missing         16
parts only       2
Name: count, dtype: int64

2. In this step, I display the descriptive statistics for the vehicle model variable.

In [26]:
df['title_status'].describe()

count      9738
unique        6
top       clean
freq       9423
Name: title_status, dtype: object

3. In this step, I display the records where the vehicle title status is missing and examine the data to determine which strategy can be applied to handle these missing values.

In [27]:
df[df['title_status'].isna()]

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
11,7316540706,https://cincinnati.craigslist.org/ctd/d/fairfi...,cincinnati,https://cincinnati.craigslist.org,4995,2012.0,fiat,500 pop,gas,59242,NaN,manual,https://images.craigslist.org/00Z0Z_jbUmVcYlwR...,"2012 Fiat 500 Pop FOR ONLY $102/mo!59,242 mi. ...",oh,39.297045,-84.563243,2021-05-03T21:03:32-0400,low,2021-05-04 01:03:32+00:00
185,7313570594,https://orangecounty.craigslist.org/ctd/d/coro...,orange county,https://orangecounty.craigslist.org,17900,2013.0,ram,1500 tradesman quad cab,gas,145499,NaN,automatic,https://images.craigslist.org/00H0H_1JFMPCYyW8...,2013 Ram 1500 Tradesman Quad Cab PRICED TO SEL...,ca,33.873436,-117.542806,2021-04-27T15:03:47-0700,medium,2021-04-27 22:03:47+00:00
243,7315211652,https://ocala.craigslist.org/ctd/d/riverview-2...,ocala,https://ocala.craigslist.org,40990,2019.0,toyota,sienna xle,gas,3700,NaN,automatic,https://images.craigslist.org/01111_grKNF8GrXz...,2019 Toyota Sienna - Wheelchair Accessible Han...,fl,27.849760,-82.364950,2021-05-01T06:35:56-0400,high,2021-05-01 10:35:56+00:00
284,7306702976,https://toledo.craigslist.org/ctd/d/chelsea-73...,toledo,https://toledo.craigslist.org,4592,2003.0,chevrolet,avalanche 1500,gas,268691,NaN,automatic,https://images.craigslist.org/00808_1IOMJuA4GL...,$73/mo - 2003 Chevrolet Avalanche 1500 BaseCre...,oh,42.300673,-84.024108,2021-04-14T12:03:01-0400,low,2021-04-14 16:03:01+00:00
310,7307609203,https://roseburg.craigslist.org/ctd/d/eugene-2...,roseburg,https://roseburg.craigslist.org,18450,2017.0,ford,mustang,gas,66049,NaN,automatic,https://images.craigslist.org/00505_4apF36sLbP...,"2017 Ford MUSTANG - $18,450 \tMayberry Motors ...",or,44.058499,-123.106176,2021-04-16T04:06:29-0700,medium,2021-04-16 11:06:29+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,7301707830,https://tricities.craigslist.org/ctd/d/bristol...,tri-cities,https://tricities.craigslist.org,8995,2013.0,honda,odyssey,gas,203112,NaN,automatic,https://images.craigslist.org/00u0u_bawW7HN8xW...,"2013 *Honda* *Odyssey* 5dr EX Van FWD - $8,995...",tn,36.541821,-82.234645,2021-04-04T13:12:27-0400,low,2021-04-04 17:12:27+00:00
9708,7313949726,https://harrisburg.craigslist.org/ctd/d/brockp...,harrisburg,https://harrisburg.craigslist.org,8900,2012.0,honda,accord,other,95674,NaN,other,https://images.craigslist.org/01212_dsfYRNhxfd...,Car Starz Call Sales at 717-401-4221 2012 Hond...,pa,41.261540,-78.704520,2021-04-28T14:25:32-0400,low,2021-04-28 18:25:32+00:00
9743,7314987181,https://nashville.craigslist.org/ctd/d/nashvil...,nashville,https://nashville.craigslist.org,20900,2014.0,lexus,rx 350,gas,70800,NaN,automatic,https://images.craigslist.org/00Q0Q_cGablAkoYV...,2014 *Lexus* *RX 350* 2014 LEXUS RX 350 SUV 1-...,tn,36.138022,-86.732261,2021-04-30T15:00:48-0500,medium,2021-04-30 20:00:48+00:00
9759,7309717260,https://savannah.craigslist.org/ctd/d/jacksonv...,savannah / hinesville,https://savannah.craigslist.org,11495,2006.0,lexus,gx 470,gas,242000,NaN,automatic,https://images.craigslist.org/00s0s_8xg4gw6aAg...,"2006 *Lexus* *GX 470* 4dr SUV 4WD - $11,495By ...",ga,30.513566,-81.621875,2021-04-20T08:01:49-0400,medium,2021-04-20 12:01:49+00:00
9883,7315557731,https://minneapolis.craigslist.org/csw/ctd/d/d...,minneapolis / st paul,https://minneapolis.craigslist.org,38943,2008.0,ford,f750 super duty - 55ft,diesel,81214,NaN,automatic,https://images.craigslist.org/00y0y_5jr8fQlu7e...,2008 Ford F750 F 750 F-750 Super Duty 55ft 55 ...,mn,45.082884,-94.334760,2021-05-01T18:03:06-0500,high,2021-05-01 23:03:06+00:00

4. In this step, I handle the missing values by filling the empty entries in the vehicle title status column with the most frequent value in the dataset. Instead of specifying it manually as a string, I obtain the mode of the column and use it to fill the missing values, then save the changes.

In [29]:
mode_status = df['title_status'].mode()
df['title_status'] = df['title_status'].fillna(mode_status[0])

5. In this step, I display the number of missing values in the vehicle title status column for the updated dataframe.

In [30]:
 count_empty_status_values = df['title_status'].isna().sum()
print("Number of Missing Values in the `title_status` Column:", count_empty_status_values)

Number of Missing Values in the `title_status` Column: 0

6. In this step, I once again display the number of fully completed records and their percentage of the total dataset. After handling all missing values, the dataset is ready for the next stage of analysis.

In [31]:
df_clean = df.dropna()
num_filled_rows = len(df_clean)
total_rows = len(df)
percentage_filled = round(((num_filled_rows / total_rows) * 100), 2)
print('Number of Complete Rows: ', num_filled_rows)
print('Percentage of Fully Completed Rows: ', percentage_filled, '%')

Number of Complete Rows:  9868
Percentage of Fully Completed Rows:  99.66 %

### Task 6. Converting the Data Type of the Vehicle's Year of Manufacture
1.  In this step, I display the dataframe information and examine the data types of the variables.

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9902 entries, 0 to 9901
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              9902 non-null   int64
 1   url             9902 non-null   object
 2   region          9902 non-null   object
 3   region_url      9902 non-null   object
 4   price           9902 non-null   int64
 5   year            9868 non-null   float64
 6   manufacturer    9902 non-null   object
 7   model           9902 non-null   object
 8   fuel            9902 non-null   object
 9   odometer        9902 non-null   int64
 10  title_status    9902 non-null   object
 11  transmission    9902 non-null   object
 12  image_url       9902 non-null   object
 13  description     9902 non-null   object
 14  state           9902 non-null   object
 15  lat             9902 non-null   float64
 16  long            9902 non-null   float64
 17  posting_date    9902 non-null   object
 18  price_category  9902 non-null   object
 19  date            9902 non-null   object
dtypes: float64(3), int64(3), object(14)
memory usage: 1.5+ MB

2. In this step, I display the descriptive statistics for the vehicle's year of manufacture and pay attention to its data type.

In [33]:
df['year'].describe()

count    9868.000000
mean     2010.909708
std         9.705988
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

3. In this step, I convert the data type of the vehicle's year of manufacture to a more appropriate integer type and then display the resulting data type for the year column.

In [34]:
# **All values that cannot be converted to numbers (for example, strings) will be replaced with NaN.**
df['year'] = pd.to_numeric(df['year'], errors='coerce')
# Converting Data to an Integer Type That Supports NaN Values
df['year'].astype('Int64')

0       2020
1       2016
2       2017
3       2013
4       2021
        ...
9897    2002
9898    2008
9899    2011
9900    2015
9901    2017
Name: year, Length: 9902, dtype: Int64

In [35]:
 print(df['year'].dtype)

float64

### Task 7. Converting Data Types in Categorical Variables

1. In this step, I display the data type of the vehicle's fuel type variable.

In [36]:
print(df['fuel'].dtype)

object

2. Categorical variables can be assigned a special data type called `category`. More details can be found in the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html). In this step, I convert the data type of the fuel type variable to `category`, save the result in the variable `series`, and display it.

In [37]:
series = df['fuel'].astype('category')

In [38]:
 print(series)

0       diesel
1        other
2          gas
3          gas
4          gas
         ...
9897       gas
9898       gas
9899       gas
9900    hybrid
9901       gas
Name: fuel, Length: 9902, dtype: category
Categories (5, object): ['diesel', 'electric', 'gas', 'hybrid', 'other']

3. In this step, I display the data type of the series and examine the structure of the output.

In [39]:
print(series.dtype)

category

4. In this step, I display the first two categories using the information from the data type output above.

In [40]:
print(series.cat.categories[:2])

Index(['diesel', 'electric'], dtype='object')

### Task 8. Outliers in the Vehicle's Year of Manufacture

1. In this step, I display the descriptive statistics for the vehicle's year of manufacture and pay attention to the boundary values and quartiles.

In [41]:
df['year'].describe()

count    9868.000000
mean     2010.909708
std         9.705988
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

2. In this step, I calculate the boundaries for normal values of the vehicle's year of manufacture using the interquartile range (IQR). I then examine whether the minimum and maximum values fall within the interval defined by these boundaries.

In [42]:
def calculate_outliers(data):
    q25 = data.quantile(0.25)
    q75 = data.quantile(0.75)
    # Calculation of the Interquartile Range (IQR)
    igr = q75 - q25
    # Outlier Boundaries
    boundaries = (q25 - 1.5 * igr, q75 + 1.5 * igr)
    return boundaries

In [43]:
 boundaries = calculate_outliers(df['year'])
boundaries

(np.float64(1994.5), np.float64(2030.5))

In [44]:
print(df['year'].min(), df['year'].max())
print(boundaries)

1915.0 2022.0
(np.float64(1994.5), np.float64(2030.5))

3. In this step, I calculate and display the number of outliers in the vehicle's year of manufacture.

In [45]:
lower, upper = boundaries
outliers = df[(df['year'] < lower) | (df['year'] > upper)]
len(outliers)

394

4. In this step, I calculate and display the proportion of outliers in the vehicle's year of manufacture.

In [47]:
outliers_percentage = len(outliers) / len(df)
print('Proportion of Outliers in the Vehicles Year of Manufacture: ', outliers_percentage, '%')

Proportion of Outliers in the Vehicles Year of Manufacture:  0.03978994142597455 %

5. In this step, I display the records where the vehicle's year of manufacture falls into the outlier range. I then examine the data to determine whether these values represent specific price categories or other features, or if they are truly outliers.

In [48]:
outliers

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,title_status,transmission,image_url,description,state,lat,long,posting_date,price_category,date
13,7317089086,https://seattle.craigslist.org/see/ctd/d/portl...,seattle-tacoma,https://seattle.craigslist.org,14995,1994.0,ford,e-series van universal by glaval designer luxu...,gas,156925,clean,automatic,https://images.craigslist.org/00r0r_13JUlXZOMl...,"Priced to Sell: $14,9951994 Ford E-Series Van ...",wa,45.391373,-122.613533,2021-05-04T20:22:11-0700,medium,2021-05-05 03:22:11+00:00
21,7312327909,https://madison.craigslist.org/cto/d/madison-1...,madison,https://madison.craigslist.org,89995,1970.0,other,oldsmobile 442,gas,111111,clean,automatic,https://images.craigslist.org/00S0S_agk7Nol4CO...,1970 Oldsmobile 442 Convertible 442 Indy Pace ...,wi,43.098400,-89.273400,2021-04-25T10:10:43-0500,high,2021-04-25 15:10:43+00:00
57,7314413105,https://inlandempire.craigslist.org/ctd/d/cost...,inland empire,https://inlandempire.craigslist.org,69888,1948.0,ford,coe,gas,1,clean,automatic,https://images.craigslist.org/00M0M_8jgBCZZuG6...,Awesome Resto-Mod COE Ford Car Hauler. Equippe...,ca,33.680100,-117.908500,2021-04-29T10:49:29-0700,high,2021-04-29 17:49:29+00:00
66,7310077530,https://hudsonvalley.craigslist.org/cto/d/bloo...,hudson valley,https://hudsonvalley.craigslist.org,5500,1990.0,other,Diahatsu,gas,30000,clean,manual,https://images.craigslist.org/00T0T_a4VRbx40ea...,1991 Daihatsu hijet 5 speed extended cab....im...,ny,41.564400,-74.430400,2021-04-20T18:30:18-0400,low,2021-04-20 22:30:18+00:00
106,7314527175,https://rapidcity.craigslist.org/ctd/d/sherman...,rapid city / west SD,https://rapidcity.craigslist.org,43500,1968.0,chevrolet,camaro,gas,43320,clean,manual,https://images.craigslist.org/00h0h_2N66LMJBAI...,1968 Chevrolet Camaro Convertible. VIN:124678N...,sd,33.637200,-96.618400,2021-04-29T15:11:01-0600,high,2021-04-29 21:11:01+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9789,7313487583,https://springfield.craigslist.org/cto/d/mount...,springfield,https://springfield.craigslist.org,3500,1974.0,jeep,cj5,gas,10000,clean,manual,https://images.craigslist.org/00G0G_cdxzaTaVqa...,1974 Jeep cj5 304 v8 4speed manual trans Da...,mo,36.331200,-92.375300,2021-04-27T14:30:28-0500,low,2021-04-27 19:30:28+00:00
9823,7311566144,https://chico.craigslist.org/cto/d/chico-1994-...,chico,https://chico.craigslist.org,16000,1994.0,ford,f250,gas,32500,clean,automatic,https://images.craigslist.org/01010_343KkgTaHo...,"Up for sale is this 32,000 original mile Ford ...",ca,39.745800,-121.844400,2021-04-23T13:51:20-0700,medium,2021-04-23 20:51:20+00:00
9846,7313676859,https://reno.craigslist.org/ctd/d/sherman-1984...,reno / tahoe,https://reno.craigslist.org,26500,1984.0,chevrolet,silverado,gas,38751,clean,automatic,https://images.craigslist.org/00r0r_czXfi4UeJF...,"1984 Chevrolet C10 Silverado, short wheelbase ...",ca,33.637200,-96.618400,2021-04-27T19:44:27-0700,high,2021-04-28 02:44:27+00:00
9874,7316458200,https://portland.craigslist.org/mlt/cto/d/port...,portland,https://portland.craigslist.org,18500,1972.0,chevrolet,other,gas,75000,clean,automatic,https://images.craigslist.org/00x0x_7FqS8iHJst...,1972 classic Chevrolet pick up custom deluxe ...,or,45.494960,-122.666988,2021-05-03T14:58:34-0700,medium,2021-05-03 21:58:34+00:00
9892,7316175335,https://orangecounty.craigslist.org/cto/d/hunt...,orange county,https://orangecounty.craigslist.org,1575,1988.0,other,1988 Nisan,gas,120000,clean,manual,https://images.craigslist.org/00B0B_5t6BpiGoz9...,Really good running 88 Nissan. Has Sun roof. B...,ca,33.654019,-117.980606,2021-05-03T07:19:18-0700,low,2021-05-03 14:19:18+00:00

6. In this step, I display the number of values for the price category among the records where the vehicle's year of manufacture is considered an outlier. I then examine whether these anomalous year values describe any specific price category better than the others.

In [49]:
outliers['price_category'].value_counts()

price_category
low       181
medium    135
high       78
Name: count, dtype: int64

7. Since the outliers in the vehicle's year of manufacture are among the minimum values, I replace those outlier values with the lower boundary. I also make sure that the year remains an integer value within the range of normal values.

In [50]:
import math
lower_int = math.ceil(lower)
df.loc[df['year'] < lower, 'year'] = lower_int

8. In this step, I display the descriptive statistics for the vehicle's year of manufacture once again to verify that all year values now fall within the boundaries of normal values.

In [51]:
df['year'].describe()

count    9868.000000
mean     2011.698318
std         6.425102
min      1995.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

### Задача 9. Loading a DataFrame with Transformation Parameters

Some feature transformations can be performed at the moment of loading the dataframe from a file.

In this step, I load the file data/vehicles_dataset.csv into a new dataframe, selecting only the necessary columns and applying the appropriate data type conversions. I refer to the documentation
 to understand the parameters usecols, parse_dates, and dtype.

The resulting dataframe should contain:

the columns price, year, and posting_date;

posting_date in datetime format;

price in float format;

year in an integer format.

While loading the data, an error may occur when reading the year column as an integer. To handle this issue, I refer to the documentation on the nullable integer data type:

https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html

Note: Pandas can represent integer data with possible missing values using arrays.IntegerArray or its aliases, which are described in the documentation.

In [52]:
vehicles_df = pd.read_csv(
'data/vehicles_dataset.csv', 
usecols=
    ['price', 'year', 'posting_date'], 
dtype={
    'price': 'float', 
    'year': 'Int64'}, 
parse_dates=['posting_date']
)

In [53]:
vehicles_df

         price  year               posting_date
0      54990.0  2020  2021-04-17 12:30:50-04:00
1      16942.0  2016  2021-05-03 15:40:21-04:00
2      35590.0  2017  2021-04-28 03:52:20-07:00
3      14500.0  2013  2021-04-17 10:08:57-04:00
4      21800.0  2021  2021-05-03 18:32:06-04:00
...        ...   ...                        ...
10045   4495.0  2002  2021-04-10 16:33:57-04:00
10046  14495.0  2008  2021-05-03 09:36:30-04:00
10047   8995.0  2011  2021-04-22 12:14:01-07:00
10048  31900.0  2015  2021-04-14 09:14:42-05:00
10049  31990.0  2017  2021-04-24 13:50:49-04:00

[10050 rows x 3 columns]

2. In this step, I display the dataframe information to ensure that the features were correctly converted during the data loading process.

In [54]:
vehicles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10050 entries, 0 to 10049
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         10050 non-null  float64
 1   year          10014 non-null  Int64
 2   posting_date  10048 non-null  object
dtypes: Int64(1), float64(1), object(1)
memory usage: 245.5+ KB

3. For the first record in the dataframe, I extract the month number from `posting_date` and display it.

In [55]:
vehicles_df.loc[0, 'posting_date'].month

4